# Définition des Variables (à compléter)
CC = c99
CFLAGS = -Wextra -pedantic -c
LDFLAGS = 

# Règles (à compléter avec des variables automatiques)
all: test_file, exemple_file

test_file: test_file.o
	$(CC) $(CFLAGS) $? -o test_file

exemple_file: exemple_file.o
	$(CC) $(CFLAGS) $? -o exemple_file

depend:
	makedepend *.c -Y.

clean:
	rm *.o test_file exemple_file

.PHONY: clean all makedepend

